import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const videos = [
  {
    _id: uuid(),
    title: "Moong Dal Dosa",
    author: "Emily",
    timeDuration: "12min",
    url: "vmnns9LDyHU",
    views: 80,
    imageUrl: "https://i3.ytimg.com/vi/vmnns9LDyHU/maxresdefault.jpg",
    rating: 5,
    category: "Breakfast",
    isMustWatch: true,
  },
  {
    _id: uuid(),
    title: "Healthy Breakfast Options",
    author: "Jack",
    timeDuration: "12min",
    views: 200,
    url: "ee0SfGSJOTc",
    imageUrl: "https://i3.ytimg.com/vi/ee0SfGSJOTc/maxresdefault.jpg",
    rating: 5,
    category: "Breakfast",
    isMustWatch: true,
  },
  {
    _id: uuid(),
    title: "Healthy Lunch Box Ideas",
    author: "Joseph",
    timeDuration: "15min",
    views: 200,
    url: "d4vAv6CG7M0",
    imageUrl: "https://i3.ytimg.com/vi/d4vAv6CG7M0/maxresdefault.jpg",
    rating: 4,
    category: "Lunch",
    isMustWatch: true,
  },
  {
    _id: uuid(),
    title: "Tasty Dinner Ideas",
    author: "Joseph",
    timeDuration: "15min",
    views: 90,
    url: "BEzASBGeEIM",
    imageUrl: "https://i3.ytimg.com/vi/BEzASBGeEIM/maxresdefault.jpg",
    rating: 4,
    category: "Dinner",
    isMustWatch: true,
  },
  {
    _id: uuid(),
    title: "Healthy Evening Snacks",
    author: "Joseph",
    timeDuration: "8min",
    views: 200,
    url: "110G3GvaZns",
    imageUrl: "https://i3.ytimg.com/vi/110G3GvaZns/maxresdefault.jpg",
    rating: 3,
    category: "Lunch",
    isMustWatch: false,
  },
  {
    _id: uuid(),
    title: " Easy Restaurant Style Recipes",
    author: "Joseph",
    timeDuration: "8min",
    views: 200,
    url: "X5j5EBLNv8",
    imageUrl: "https://i3.ytimg.com/vi/-X5j5EBLNv8/maxresdefault.jpg",
    rating: 3,
    category: "Dinner",
    isMustWatch: false,
  },
  {
    _id: uuid(),
    title: "Creative Recipes to Try",
    author: "Joseph",
    timeDuration: "15min",
    views: 90,
    url: "mbo5wXh1lWE",
    imageUrl: "https://i3.ytimg.com/vi/mbo5wXh1lWE/maxresdefault.jpg",
    rating: 2,
    category: "Lunch",
    isMustWatch: false,
  },
  {
    _id: uuid(),
    title: "HEALTHY SANDWICH Recipes",
    author: "Joseph",
    timeDuration: "5min",
    views: 200,
    url: "FToH1APJjg0",
    imageUrl: "https://i3.ytimg.com/vi/FToH1APJjg0/maxresdefault.jpg",
    rating: 2,
    category: "Breakfast",
    isMustWatch: false,
  },

  {
    _id: uuid(),
    title: "Healthy & Tasty Ice Cream",
    author: "Joseph",
    timeDuration: "8min",
    views: 90,
    url: "jwmNjJgZanM",
    imageUrl: "https://i3.ytimg.com/vi/jwmNjJgZanM/maxresdefault.jpg",
    rating: 1,
    category: "Dinner",
    isMustWatch: false,
  },

  {
    _id: uuid(),
    title: " Healthy Dessert Ideas",
    author: "Joseph",
    timeDuration: "8min",
    views: 200,
    url: "hLrny7Xjy2g",
    imageUrl: "https://i3.ytimg.com/vi/hLrny7Xjy2g/maxresdefault.jpg",
    rating: 1,
    category: "Dinner",
    isMustWatch: false,
  },
  {
    _id: uuid(),
    title: "SPROUTS - Easy Preparation",
    author: "Joseph",
    timeDuration: "8min",
    views: 200,
    url: "g4GSHgFfaMA",
    imageUrl: "https://i3.ytimg.com/vi/g4GSHgFfaMA/maxresdefault.jpg",
    rating: 1,
    category: "Breakfast",
    isMustWatch: false,
  },
  {
    _id: uuid(),
    title: "Refreshing Drinks to Make 🔥",
    author: "Joseph",
    timeDuration: "8min",
    views: 200,
    url: "ucOmGiNg1kg",
    imageUrl: "https://i3.ytimg.com/vi/ucOmGiNg1kg/maxresdefault.jpg",
    rating: 1,
    category: "Lunch",
    isMustWatch: false,
  },
  {
    _id: uuid(),
    title: "Homemade Peanut Butter Recipe",
    author: "Joseph",
    timeDuration: "8min",
    views: 200,
    url: "0mrrZYTvQ44",
    imageUrl: "https://i3.ytimg.com/vi/0mrrZYTvQ44/maxresdefault.jpg",
    rating: 1,
    category: "Breakfast",
    isMustWatch: false,
  },
];
